export const CREATE_BENIFICIARY = "CREATE_BENIFICIARY";
export const GET_BENIFICIARY = "GET_BENIFICIARY";
export const GET_ALL_BENIFICIARY = "GET_ALL_BENIFICIARY";
export const UPDATE_BENIFICIARY = "UPDATE_BENIFICIARY";
export const DELETE_BENIFICIARY = "DELETE_BENIFICIARY";
export const RESET_STATE = 'RESET_STATE';

